version: "3.7"

networks:
  jaegernetwork:
    driver: bridge

services:

  hellospan:
      build:
        context: .
      container_name: hellospan
      restart: unless-stopped
      ports:
        - 5000:5000
      volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      networks:
        - jaegernetwork

  jaeger:
    image: jaegertracing/all-in-one:latest
    container_name: jaeger
    restart: unless-stopped
    ports:
      - "5775:5775/udp"
      - "6831:6831/udp"
      - "6832:6832/udp"
      - "5778:5778"
      - "16686:16686"
      - "14268:14268"
      - "9411:9411"
    environment:
      - COLLECTOR_ZIPKIN_HTTP_PORT=9411
      # - QUERY_BASE_PATH=/jaeger
      # - SPAN_STORAGE_TYPE=elasticsearch
      # - ES_SERVER_URLS=http://elasticcoord1:9201
    networks:
      - jaegernetwork
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
